In [1]:
# NumPy 예제
import numpy as np

In [4]:
# 1차원 배열 생성
arr1 = np.zeros(4)
print(arr1)

arr2 = np.empty(4)
print(arr2)

list = [1, 2, 3, 4]
arr3 = np.array(list)
print(arr3)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[1 2 3 4]


In [5]:
arr4 = np.zeros((2,3))
print(arr4)
print(f"차원수 : {arr4.ndim}")
print(f"모양 : {arr4.shape}")
print(f"전체개수 : {arr4.size}")
print(f"타입 : {arr4.dtype}")

[[0. 0. 0.]
 [0. 0. 0.]]
차원수 : 2
모양 : (2, 3)
전체개수 : 6
타입 : float64


In [ ]:
# 배열
arr5 = np.array([1,2,3,4,5,6])
print(arr5)
arr6 = arr5.reshape(2,3)
print(arr6)
arr7 = arr5.reshape(3,-1)
print(arr7)
arr8 = arr5.reshape(-1,1)
print(arr8)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
# 인덱싱과 슬라이싱
arr9 = np.array([[1,2,3,],[4,5,6]])
print(arr9)

[[1 2 3]
 [4 5 6]]
