In [1]:
# 전이학습 모델 로드
from tensorflow.keras.applications import mobilenet_v2

model = mobilenet_v2.MobileNetV2(weights='imagenet', include_top=True)

In [2]:
# 테스트할 이미지 준비
import requests
from tensorflow.keras.preprocessing import image
from io import BytesIO

url = 'https://th.bing.com/th/id/OIP.tE_T4HoqYlY_KruLJ_5IsgHaF7?w=222&h=180&c=7&r=0&o=7&pid=1.7&rm=3'

response = requests.get(url)
img = image.load_img(BytesIO(response.content), target_size=(224,224))

In [3]:
import numpy as np
# 이미지 전처리 => 입력 형태 맞추기, 이미지를 배열로
X = image.img_to_array(img)
print(X.shape)
X = np.expand_dims(X, axis=0)
print(X.shape)

(224, 224, 3)
(1, 224, 224, 3)


In [4]:
# MoileNetV2 전용 전처리
print(X)
X = mobilenet_v2.preprocess_input(X)
print(X)

[[[[ 34.   9.   6.]
   [ 34.   9.   6.]
   [ 34.   9.   6.]
   ...
   [ 34.  31.  35.]
   [ 34.  31.  35.]
   [ 33.  30.  33.]]

  [[ 34.   9.   6.]
   [ 34.   9.   6.]
   [ 34.   9.   6.]
   ...
   [ 33.  30.  33.]
   [ 33.  30.  33.]
   [ 33.  30.  33.]]

  [[ 35.  10.   7.]
   [ 35.  10.   7.]
   [ 35.  10.   7.]
   ...
   [ 33.  30.  33.]
   [ 33.  30.  33.]
   [ 33.  30.  33.]]

  ...

  [[ 29.  42.   6.]
   [ 28.  41.   4.]
   [ 30.  43.   7.]
   ...
   [ 72.  91.  44.]
   [ 86. 105.  58.]
   [ 70.  89.  42.]]

  [[ 37.  50.  14.]
   [ 25.  38.   2.]
   [ 49.  61.  25.]
   ...
   [ 53.  72.  24.]
   [ 93. 112.  65.]
   [ 82. 101.  53.]]

  [[ 41.  53.  17.]
   [ 50.  63.  26.]
   [ 32.  45.   9.]
   ...
   [ 65.  84.  37.]
   [ 65.  84.  37.]
   [ 78.  97.  50.]]]]
[[[[-0.73333335 -0.92941177 -0.9529412 ]
   [-0.73333335 -0.92941177 -0.9529412 ]
   [-0.73333335 -0.92941177 -0.9529412 ]
   ...
   [-0.73333335 -0.75686276 -0.7254902 ]
   [-0.73333335 -0.75686276 -0.7254902 ]
   [-0

In [5]:
# 예측
p = model.predict(X)
p

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[3.33927237e-05, 1.02533095e-05, 1.71306783e-05, 1.55922771e-05,
        1.46441253e-05, 1.19691416e-04, 5.86982424e-05, 2.77918662e-05,
        9.75465664e-05, 1.12106964e-05, 2.66354182e-05, 3.03173256e-05,
        4.47772727e-05, 1.10019491e-05, 5.03812735e-05, 2.81225512e-05,
        2.39372093e-05, 1.68301776e-05, 8.25105508e-06, 7.59530076e-06,
        3.43017491e-05, 8.46541443e-05, 1.81373816e-05, 6.63067767e-05,
        2.29513153e-05, 2.78992302e-05, 2.90289317e-05, 3.46407141e-05,
        2.81735283e-05, 8.67969175e-06, 5.17923654e-05, 2.71588924e-05,
        3.93157570e-05, 1.73784574e-05, 2.18915302e-05, 2.64968094e-05,
        2.70381261e-05, 3.86065367e-05, 3.87566033e-05, 2.15716282e-05,
        9.01675812e-05, 2.80518088e-05, 4.43440258e-05, 1.78805039e-05,
        7.00224991e-05, 5.86017013e-05, 2.86783943e-05, 6.06475187e-05,
        3.86257598e-05, 2.67259275e-05, 2.30381556e-05, 1.13300648e-05,
        4.49083927e-05, 7.04532722e-05, 9.52016198e-05, 2.825443

In [17]:
# 결과를 해석
results = mobilenet_v2.decode_predictions(p,top=3)[0]

print('-'*30)
for i, (_, label, prob) in enumerate(results):
	print(f'{i+1}. {label}:{prob*100:.2f}%')
print('-'*30)

------------------------------
1. Samoyed:94.55%
2. white_wolf:0.40%
3. Great_Pyrenees:0.36%
------------------------------


In [18]:
from tensorflow.keras.applications import mobilenet_v2
import requests
from io import BytesIO
def predict_img_url(url):
	# 모델 불러오기. 분류기 포함 (1000개의 분류)
	model = mobilenet_v2.MobileNetV2(weights='imagenet', include_top=True)
	# 이미지 정보 가져오기
	response = requests.get(url)
	# 가져온 이비지를 바이트형태로 변환
	img = image.load_img(BytesIO(response.content), target_size=(224,224))

	# 이미지 전처리 => 입력 형태 맞추기, 이미지를 배열로
	X = image.img_to_array(img)
	X = np.expand_dims(X, axis=0)

	# MobileNetV2 전용 전처리
	X = mobilenet_v2.preprocess_input(X)

#	예특
	predicts = model.predict(X)

	# 4. 결과 해석 (중요: 함수 내부의 예측값인 'predicts'를 사용해야 함)
  # decode_predictions를 사용하여 상위 3개를 가져옵니다.
	current_results = mobilenet_v2.decode_predictions(predicts, top=3)[0]
	print('-'*30)
	for i, (_, label, prob) in enumerate(current_results):
		print(f'{i+1}. {label}:{prob*100:.2f}%')
	print('-'*30)
	

In [19]:
# 고양이 이미지로 테스트
# 1. 
#
#
predict_img_url('https://th.bing.com/th/id/OIP.m5JFARFGcfnn1v4oRhxb_AHaGb?w=166&h=180&c=7&r=0&o=7&pid=1.7&rm=3')

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
------------------------------
1. tabby:57.93%
2. tiger_cat:17.33%
3. Egyptian_cat:4.26%
------------------------------
