In [2]:
# 아나콘다에서 설치
!pip install tensorflow
# 파이썬 터미널에서 설치
# pip install tensorflow

In [5]:
리스트1 = [1, 2, 3]
리스트2 = [[4], [5], [6]]
리스트3 = [7, 8, 9]
print(리스트1 + 리스트3) 
# 행렬곱
# 리스트1과 리스트2를 행렬곱 결과를 확인하려면...
행렬곱 = (리스트1[0] * 리스트2[0][0] + 리스트1[1] * 리스트2[1][0] +리스트1[2] * 리스트2[2][0])
print(행렬곱)

[1, 2, 3, 7, 8, 9]
32


In [6]:
# 텐서 : 수학적으로 3차원 이상의 행렬을 의미
# 0차원 : 스칼라, 1차원 : 벡터, 2차원 : 행렬, 3차원이상 : 텐서
# 텐서만들기
# 1. 상수
import tensorflow as tf
텐서1 = tf.constant([1,2,3])
텐서2 = tf.constant([
	[4],
	[5],
	[6]
	])
텐서3 = tf.constant([7,8,9])

In [9]:
print(텐서1 + 텐서3) # -, *, / 다 가능
print(tf.add(텐서1, 텐서3))
print(tf.subtract(텐서1, 텐서3))
print(tf.multiply(텐서1, 텐서3))
print(tf.divide(텐서1, 텐서3))

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([-6 -6 -6], shape=(3,), dtype=int32)
tf.Tensor([ 7 16 27], shape=(3,), dtype=int32)
tf.Tensor([0.14285714 0.25       0.33333333], shape=(3,), dtype=float64)


In [ ]:
# 행렬곱은 아무떄나 가능한게 아님
# 행렬 형태가 맞아야 함
# (m x n)형렬과 (n x I)행렬 행렬곱 가능 
# 텐서1과 텐서2를 행렬곱하기 위해 텐서1의 행렬을 맞추는 작업
# 텐서1은 벡터
텐서1_reshape = tf.reshape(텐서1, (1,-1)) # 텐서2(3x1행렬)과 곱하기 위해서 1x3행렬로 변환
텐서1_reshape.shape

TensorShape([1, 3])

In [11]:
print(tf.matmul(텐서1_reshape,텐서2))

tf.Tensor([[32]], shape=(1, 1), dtype=int32)


In [15]:
# 변수 선언하기 => 가중치 w1,w2
w = tf.Variable([3,2,1])
w

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 2, 1], dtype=int32)>

In [16]:
# 변수값 수정
w.assign([1,2,3])
# w=[1,2,3] # 안됨 리스트로 덮어쓰기 됨
w

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [17]:
# 0으로 채워진 텐서 만들기
제로텐서 = tf.zeros([4,2,3]) # 4페이지 2줄 3글자
제로텐서

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [22]:
x = tf.Variable(3.0) # x = 3
# 기울기 구하기 y=x^2 함수에서 x가 3일 때 기울기를 구함
# y=x^2의 기울기함수는 y=2x(x^2을 미분하면)
# 함수 값 (y): x가 3일 때 x^2은 얼마인가? → 9.0
# 기울기 (dy/dx): x가 3일 때 "x를 아주 조금 변화시키면 $y$는 얼마나 빨리 변하는가?" → 6.0
with tf.GradientTape() as tape:
	y = x ** 2

dy_dx = tape.gradient(y, x)
print(dy_dx.numpy())


6.0


In [23]:
# 키 데이터와 신발 데이터를 이용하여 학습하고, 키 데이터를 이용하여 신발 사이즈를 예측하는 예제
# 저수준으로 작성 => 직접 하나하나 작성
import tensorflow as tf
키데이터 = tf.constant([170, 180, 175, 160], dtype=tf.float32)
신발데이터 = tf.constant([260, 270, 265, 255], dtype=tf.float32)

In [27]:
# 각 원소를 제곱
리스트 = [1.0,2.0,3.0]
제곱 = tf.square(리스트)
print(제곱)
제곱평균 = tf.reduce_mean(제곱)
print(제곱평균)

tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)
tf.Tensor(4.6666665, shape=(), dtype=float32)


In [33]:
# 신발 = w(가중치) * 키데이터 + b(편향)
w = tf.Variable(0.1) # 초기 임의의 값
b = tf.Variable(0.1) # 초기 임의의 값
# 옵티마이저 중 Adam 선택
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range(1000):
	with tf.GradientTape() as tape:
		# 신발 = w(가중치) * 키데이터 + b(편향)
		예측값 = w * 키데이터 + b

		# 오차 : 평균 오차 제곱
		# 손실함수 중 평균 오차 제곱(MSE)를 선택해서 오차를 계산
		오차 = tf.reduce_mean(tf.square(신발데이터 - 예측값))
	# 가울기를 계산
	기울기 = tape.gradient(오차, [w,b])
	# 기울기를 이용하여 가중치 업데이터
	opt.apply_gradients(zip(기울기,[w,b]))

	if i % 100 == 0:
		print(f'{i}단계 : w = {w.numpy():.4f}, b = {b.numpy():.4f}, 오차 = {오차.numpy():.4f}')

0단계 : w = 0.2000, b = 0.2000, 오차 = 60183.4922
100단계 : w = 1.5205, b = 1.5477, 오차 = 34.6516
200단계 : w = 1.5220, b = 1.6023, 오차 = 34.3356
300단계 : w = 1.5216, b = 1.6721, 오차 = 34.3009
400단계 : w = 1.5211, b = 1.7568, 오차 = 34.2589
500단계 : w = 1.5206, b = 1.8554, 오차 = 34.2099
600단계 : w = 1.5199, b = 1.9673, 오차 = 34.1545
700단계 : w = 1.5192, b = 2.0922, 오차 = 34.0926
800단계 : w = 1.5184, b = 2.2299, 오차 = 34.0245
900단계 : w = 1.5175, b = 2.3807, 오차 = 33.9499


In [34]:
측정키 = 173
예측신발 = w.numpy() * 측정키 + b.numpy()
print(f'측정키 : {측정키}, 에측신발사이즈 : {예측신발:.2f}')
print(f'가중치 : {w.numpy():.2f}, 편향 : {b.numpy():.2f}')

측정키 : 173, 에측신발사이즈 : 264.91
가중치 : 1.52, 편향 : 2.54
